# Hetzner Storage Box WebDAV
# Hetzner Storage Box WebDAV
hetzner.host=u547198.your-storagebox.de
hetzner.sftp.port=22
hetzner.username=u547198
hetzner.password=S1fr@hetzner
hetzner.api.key=YSXCmRJvJ83qhoAGCyo0YeIJRZDmZ1uZEgYXu2nbiuuR6nZVKUG1rre0fdudnDyD
hetzner.api.token=YSXCmRJvJ83qhoAGCyo0YeIJRZDmZ1uZEgYXu2nbiuuR6nZVKUG1rre0fdudnDyD



# Upload limits (povećaj ako ti trebaju veći fajlovi)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.from=noreply@studio27.rs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
