# Hetzner Storage Box WebDAV
# Hetzner Storage Box WebDAV
hetzner.host=u547198.your-storagebox.de
hetzner.sftp.port=22
hetzner.username=u547198
hetzner.password=S1fr@hetzner
hetzner.api.key=YSXCmRJvJ83qhoAGCyo0YeIJRZDmZ1uZEgYXu2nbiuuR6nZVKUG1rre0fdudnDyD
hetzner.api.token=YSXCmRJvJ83qhoAGCyo0YeIJRZDmZ1uZEgYXu2nbiuuR6nZVKUG1rre0fdudnDyD



# Upload limits (povećaj ako ti trebaju veći fajlovi)
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# OAuth2 Configuration for Google (Local Development)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:your-client-id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:your-client-secret}
spring.security.oauth2.client.registration.google.scope=profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google

# Custom application properties for cookies (Local)
app.cookie.domain=${APP_COOKIE_DOMAIN:localhost}
app.cookie.secure=${APP_COOKIE_SECURE:false}
app.cookie.same-site=${APP_COOKIE_SAME_SITE:Lax}
app.frontend.url=${APP_FRONTEND_URL:http://localhost:3000}
